name: Performance Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches: [main]

jobs:
  test:
    name: Performance Tests
    runs-on: ubuntu-latest

    services:
      postgres:
        image: bitnami/postgresql
        ports:
          - 5432:5432
        env:
          POSTGRESQL_USERNAME: postgres
          POSTGRESQL_PASSWORD: postgres
          POSTGRESQL_DATABASE: modular-pets

    steps:
      - uses: actions/checkout@v4

      - name: Set up Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: 1.1.38

      - name: Install Dependencies
        run: bun install --frozen-lockfile
      
      - name: Install K6
        run: sudo apt-get update && sudo apt-get install -y k6

      - name: Start Development Server
        run: bun run dev
        env:
          DATABASE_URL: "postgresql://postgres:postgres@localhost:5432/modular-pets"

      - name: Setup K6
        uses: grafana/setup-k6-action@v1
      - name: Run local k6 test
        uses: grafana/run-k6-action@v1
        with:
          path: scripts/performance-test.ts