name: Test E2E

on:
  push:
    branches:
      - main
  pull_request:
    branches: [main]

jobs:
  build:
    name: Test E2E
    runs-on: ubuntu-latest

    services:
      postgres:
        image: bitnami/postgresql
        ports:
          - 5432:5432
        env:
          POSTGRESQL_USERNAME: postgres
          POSTGRESQL_PASSWORD: postgres
          POSTGRESQL_DATABASE: modular-pets

    steps:
      - uses: actions/checkout@v4

      - name: Set up Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: 1.1.38

      - name: Install Dependencies
        run: bun install --frozen-lockfile

      - name: Run E2E Tests
        run: |
          bun run migrate &&
          bun run test:e2e
        env:
          DATABASE_URL: "postgresql://postgres:postgres@localhost:5432/modular-pets"