name: Unit Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches: 
      - main

jobs:
  test:
    name: Unit Tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: 1.2.2

      - name: Install Dependencies
        run: bun install --frozen-lockfile

      - name: Run Unit Tests
        run: bun run test
        env:
          DATABASE_URL: "postgresql://just-to-avoid-error:just-to-avoid-error@localhost:5432/just-to-avoid-error"
          PRIVATE_TOKEN_KEY_PATH: "keys/test/token-private.pem"
          PUBLIC_TOKEN_KEY_PATH: "keys/test/token-public.pem"