name: Unit Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches: 
      - main

jobs:
  test:
    name: Unit Tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: 1.1.38

      - name: Install Dependencies
        run: bun install --frozen-lockfile

      - name: Run Unit Tests
        run: bun run test